# Generated by Django 3.1.7 on 2021-03-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('e_mail', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('reg_info', models.TextField(max_length=2000, verbose_name='Текст записи')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'db_table': 'guest',
            },
        ),
    ]
